<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Orders.aspx.cs" Inherits="WPLProject.admin.Orders" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Admin Portal</title>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="../styles/all.min.css" />
    <link rel="stylesheet" href="../styles/style.css" />
</head>
<body>
    <form id="form1" runat="server">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 light-primary-color primary-text-color d-flex justify-content-between">
                    <div class="logo">
                        <img class="img-fluid logo" src="../images/logo.jpg" alt="Logo" />
                    </div>
                    <div class="d-flex align-items-center justify-content-end">
                        <div>
                            <i class="fa fa-hand-peace"></i>
                            <asp:Label ID="welcomeLbl" runat="server" Text=""></asp:Label>
                        </div>
                        <button class="btn" id="logoutBtn" runat="server" onserverclick="logoutBtn_ServerClick">
                            <i class="fas fa-sign-out-alt"></i>Signout
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container blob">
            <div class="row my-5 justify-content-center">
                <div class="col-12 text-center">
                    <h1>
                        <a href="Admin.aspx"><i class="fas fa-2x fa-chevron-left"></i></a>
                        All Orders Report
                    </h1>
                    <p>Edit Details or Delete your Orders here</p>
                </div>
                <div class="col-6 text-center">
                    <i class="fas fa-file-signature"></i>
                    <asp:Label ID="NoSale" runat="server" Text="No Sales"></asp:Label>
                </div>
                <div class="col-6 text-center">
                    <i class="fas fa-dollar-sign"></i>
                    <asp:Label ID="totalAmount" runat="server" Text="No Amount"></asp:Label>
                </div>
            </div>
            <div class="row my-5">
                <div class="col-12">
                    <asp:GridView
                        ID="GridView1"
                        runat="server"
                        AutoGenerateColumns="False"
                        DataKeyNames="orderId"
                        DataSourceID="SqlDataSource1"
                        CssClass="table table-light"
                        AllowSorting="True"
                        AutoGenerateEditButton="True"
                        AutoGenerateDeleteButton="True"
                        EmptyDataText="No Orders found"
                        AllowPaging="True"
                        OnRowCommand="GridView1_OnRowCommand"
                        >
                        <Columns>
                            <asp:BoundField DataField="orderId" HeaderText="orderId" InsertVisible="False" ReadOnly="True" SortExpression="orderId" />
                            <asp:BoundField DataField="productid" HeaderText="productid" ReadOnly="True" SortExpression="productid" />
                            <asp:BoundField DataField="userId" HeaderText="userId" ReadOnly="True" SortExpression="userId" />
                            <asp:BoundField DataField="amount" HeaderText="amount" SortExpression="amount" />
                            <asp:BoundField DataField="quantity" HeaderText="quantity" SortExpression="quantity" />
                            <asp:TemplateField ShowHeader="true" HeaderText="Add Order">
                                <ItemTemplate>
                                    <asp:Button ID="ViewRep" CssClass="btn btn-small" runat="server" CausesValidation="false" CommandName="sendRep"
                                        Text="View Report" CommandArgument='<%# Eval("productId") + "," + Eval("userId") + "," + Eval("orderId") %>' />
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                    <asp:SqlDataSource
                        ID="SqlDataSource1"
                        runat="server"
                        ConnectionString="<%$ ConnectionStrings:db_PaperConnectionString %>"
                        SelectCommand="SELECT * FROM [tb_sales] ORDER BY [orderId]"
                        UpdateCommand="UPDATE [tb_sales] SET amount=@amount,quantity=@quantity WHERE orderId=@orderId"
                        DeleteCommand="DELETE FROM [tb_sales] WHERE orderId=@orderId"></asp:SqlDataSource>

                </div>
            </div>
        </div>
        <div class="light-primary-color w-100">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <hr />
                        <p>
                            Copyright &copy;      
                            <p>Copyright &copy; <%: DateTime.Now.Year %>. All Rights Reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>
