<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Products.aspx.cs" Inherits="WPLProject.admin.Products" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Admin Portal</title>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="../styles/all.min.css" />
    <link rel="stylesheet" href="../styles/style.css" />
</head>
<body>
    <form id="form1" runat="server">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 light-primary-color primary-text-color d-flex justify-content-between">
                    <div class="logo">
                        <img class="img-fluid logo" src="../images/logo.jpg" alt="Logo" />
                    </div>
                    <div class="d-flex align-items-center justify-content-end">
                        <div>
                            <i class="fa fa-hand-peace"></i>
                            <asp:Label ID="welcomeLbl" runat="server" Text=""></asp:Label>
                        </div>
                        <button class="btn" id="logoutBtn" runat="server" onserverclick="logoutBtn_ServerClick">
                            <i class="fas fa-sign-out-alt"></i>Signout
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container blob">
            <div class="row my-5 justify-content-center">
                <div class="col-12 text-center">
                    <h1>
                        <a href="Admin.aspx"><i class="fas fa-2x fa-chevron-left"></i></a>All Product
                    </h1>
                    <p>Edit Details or Delete Products</p>
                </div>
                <div class="col-12">

                    <asp:GridView 
                        ID="GridView1" 
                        CssClass="table table-light" 
                        runat="server" 
                        AllowSorting="True" 
                        AutoGenerateColumns="False" 
                        DataKeyNames="productId" 
                        DataSourceID="SqlDataSource1"
                        AutoGenerateEditButton="True"
                        AutoGenerateDeleteButton="True"
                        EmptyDataText="No Results found. Please add a Product" 
                        AllowPaging="True"
                        EnableSortingAndPagingCallbacks="True"
                    >
                        <Columns>
                            <asp:BoundField DataField="productId" HeaderText="Product Id" InsertVisible="False" ReadOnly="True" SortExpression="productId" />
                            <asp:BoundField DataField="productName" HeaderText="Product Name" SortExpression="productName" />
                            <asp:BoundField DataField="productType" HeaderText="Product Type" SortExpression="productType" />
                            <asp:BoundField DataField="productDesc" HeaderText="Product Description" SortExpression="productDesc" />
                            <asp:BoundField DataField="price" HeaderText="Price" SortExpression="price" />
                        </Columns>
                    </asp:GridView>
                    <asp:SqlDataSource 
                        ID="SqlDataSource1" 
                        runat="server" 
                        ConnectionString="<%$ ConnectionStrings:db_PaperConnectionString %>" 
                        SelectCommand="SELECT * FROM [tb_product] ORDER BY [productId]"
                        UpdateCommand="UPDATE [tb_product] SET productName=@productName,productType=@productType,productDesc=@productDesc,price=@productDesc WHERE productId=@productId"
                        DeleteCommand="DELETE FROM [tb_product] WHERE productId=@productId"
                    ></asp:SqlDataSource>

                </div>
            </div>
        </div>
        <div class="light-primary-color w-100">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <hr />
                        <p>Copyright &copy; <%: DateTime.Now.Year %>. All Rights Reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>
